### ISSUE TITLE
failed to authorize account

### ISSUE THREAD

**Issue by yangxuan8282** [armdrone/drone#1]
hi, I'm trying to run drone on raspberry pi with [armdrone/drone](https://hub.docker.com/r/armdrone/drone/), but got authorize issues

```
$ docker-compose up
WARNING: Found orphan containers (markline, Gogs, letsencrypt-nginx-proxy-companion, Portainer, nginx-proxy) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating Drone
Attaching to Drone
Drone    | time="2017-02-17T04:49:30Z" level=info msg="using database driver sqlite3" 
Drone    | time="2017-02-17T04:49:30Z" level=info msg="using database config /var/lib/drone/drone.sqlite" 
Drone    | time="2017-02-17T04:49:30Z" level=info msg="registered docker daemon unix:///var/run/docker.sock" 
Drone    | time="2017-02-17T04:49:30Z" level=info msg="registered docker daemon unix:///var/run/docker.sock" 
Drone    | time="2017-02-17T04:49:30Z" level=info msg="starting server :80" 
Drone    | [GIN] 2017/02/17 - 04:49:37 | 303 |     346.047µs | 172.21.0.1 |   GET     /
Drone    | [GIN] 2017/02/17 - 04:49:37 | 200 |    1.702263ms | 172.21.0.1 |   GET     /login
Drone    | [GIN] 2017/02/17 - 04:49:37 | 200 |    7.690053ms | 172.21.0.1 |   GET     /static/styles_gen/style.css
Drone    | [GIN] 2017/02/17 - 04:49:38 | 200 |    1.685857ms | 172.21.0.1 |   GET     /static/images/logo_dark.svg
Drone    | [GIN] 2017/02/17 - 04:49:40 | 303 |    1.316026ms | 172.21.0.1 |   GET     /authorize
Drone    | time="2017-02-17T04:49:43Z" level=error msg="cannot authenticate user. Error exchanging token. Post https://github.com/login/oauth/access_token: x509: failed to load system roots and no roots provided" 
Drone    | [GIN] 2017/02/17 - 04:49:43 | 303 |  843.696249ms | 172.21.0.1 |   GET     /authorize
Drone    | [GIN] 2017/02/17 - 04:49:43 | 200 |     676.878µs | 172.21.0.1 |   GET     /login
Drone    | [GIN] 2017/02/17 - 04:49:44 | 304 |    5.451422ms | 172.21.0.1 |   GET     /static/styles_gen/style.css
Drone    | [GIN] 2017/02/17 - 04:49:44 | 304 |    1.392551ms | 172.21.0.1 |   GET     /static/images/logo_dark.svg
^CGracefully stopping... (press Ctrl+C again to force)
Stopping Drone ... done
```

my docker compose file:

```
version: '2'

services:
  drone:
    image: armdrone/drone
    container_name: Drone
    restart: always
    expose:
      - 80
    volumes:
      - ./data:/var/lib/drone
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REMOTE_DRIVER=github
      - REMOTE_CONFIG=https://github.com?client_id=<CLIENT_ID>&client_secret=<CLIENT_SECRET
      - PLUGIN_FILTER=armdrone/*
      - GIN_MODE=release
      - VIRTUAL_HOST=drone.mydomain.com
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=drone.mydomain.com
      - LETSENCRYPT_EMAIL=my@email.com

networks:
  default:
    external:
      name: proxy-network
```
